@startuml
Mari -> Apple: Oi, tudo bem?
Apple --> Mari: Tudo bem e vc
Mari -> Apple: Estou aprendendo Swift!!
@enduml

![Diagrama](https://www.plantuml.com/plantuml/png/SoWkIImgAStDuV9DBCfKqBLJS2meo4crKl3Fr54eAKt9LqXApRNd0Wigw0AbGSgi54AWCWgf2cN9w5fTYqloInKI2ufIyrA0A5yXk3mphKHHaSi1o0DQ1G00)
