@startuml

' ===== ENUMS =====
enum NivelExperiencia {
  iniciante
  intermediario
  avancado
}

enum CategoriaAula {
    zen
    fitness
    luta
}

enum NomeAula {
  musculacao
  spinning
  yoga
  pilates
  jiuJitsu
}

enum TipoContrato {
  Mensal
  Trimestral
  Semestral
  Anual
}

enum NomePlano{
    Bronze
    Prata
    Ouro
}

' ===== STRUCTS  =====

struct Pagamento  {
  valor: Double
  metodo: MetodoPagamento
}

struct PacoteFechado  {
  nome: NomePlano
  complemplaCategorias: List<CategoriaAula>
  valor: Double
}

struct PacoteContratado  {
  pacote: PacoteFechado
  tipoContrato: TipoContrato

}

struct BancoDePacotes <<repository>> {
  catalogo: List<PacoteFechado>
}

struct AlunoRepository <<repository>> {
  alunos: [String: Aluno]
  nome: String
  idade: Int
  cpf: String
  email: String
  telefone: String
  matricula: String
  nivelExperiencia: NivelExperiencia
  pacoteContratado: PacoteContratado
}
' ===== CLASSES =====

class ServicoExtra {
  nome: String
  valor: Double
  tipo: TipoServico
}

class Aula {
  nome: ListNomeAula
  categoria: CategoriaAula
  //horario: Horario
  capacidade: Int
}

class Pessoa {
  nome: String
  idade: Int
  cpf: String
  email: String
  telefone: String
}

class Aluno extends Pessoa {
  matricula: String
  nivelExperiencia: NivelExperiencia
  pacoteContratado: PacoteContratado
  Bool :cadastroAtivo
  Pagamento: comprovanteMatricula
}

class Professor extends Pessoa {
  matricula: String
  aulas: List<NomeAula>
}

class GeradorMatriculaAluno {
  contador: Int
}

class GeradorMatriculaProfessor {
  contador: Int
}
'class Contrato {
'  dataInicio: Date
'  ativo: Bool
'}

class CentroMindfulness {
    AlunoRepository : Aluno
  cadastrarAluno(AlunoRepository)
  buscarAluno (AlunoRepository)
  atualizarAluno (AlunoRepository)
  removerAluno (AlunoRepository)
  }

  class ExibirCadastro {
    printMensagemSucesso()
  }


' ===== RELAÇÕES =====
Pessoa "1" -- "0..1" Aluno
Pessoa "1" -- "0..1" Professor

Aluno "1" --> "1" PacoteFechado 
PacoteFechado "1" --> "1" PacoteContratado
PacoteContratado "1" --> "1" Pagamento
Pagamento "1" --> "1" CentroMindfulness
CentroMindfulness ..> ExibirCadastro : cadastrarAluno()
Professor "1" --> "0..*" Aula


@enduml