@startuml

' ===== ENUMS =====
enum NivelExperiencia {
  iniciante
  intermediario
  avancado
}

enum CategoriaAula {
    zen
    fitness
    luta
}

enum NomeAula {
  musculacao
  spinning
  yoga
  pilates
  jiuJitsu
}

enum TipoContrato {
  Mensal
  Trimestral
  Semestral
  Anual
}

enum NomePlano{
    Bronze
    Prata
    Ouro
}

' ===== STRUCTS  =====

class Pagamento <<struct>> {
  valor: Double
  metodo: MetodoPagamento
}

' ===== CLASSES =====
class Aula {
  nome: NomeAula
  categoria: CategoriaAula
  //horario: Horario
  capacidade: Int
}

class PacoteFechado {
  nome: NomePlano
  tipoContrato: TipoContrato
  descricaoComposicao: List<CategoriaAula>
  valor: Double
}

class Pessoa {
  nome: String
  idade: Int
  cpf: String
  email: String
  telefone: String
}

class Aluno extends Pessoa {
  matricula: String
  nivelExperiencia: NivelExperiencia
  pacoteContratado: PacoteContratado
}

class Professor extends Pessoa {
  matricula: String
  modalidades: NomeAula
}



'class Contrato {
'  dataInicio: Date
'  ativo: Bool
'}

' ===== RELAÇÕES =====
Pessoa "1" -- "0..1" Aluno
Pessoa "1" -- "0..1" Professor

Aluno "1" --> "1" PacoteContratado
PacoteContratado "1" --> "1" PacoteFechado

Professor "1" --> "0..*" Aula

@enduml