@startuml

' ===== ENUMS =====
enum NivelExperiencia {
  iniciante
  intermediario
  avancado
}

enum CategoriaAula {
    zen
    fitness
    luta
}

enum NomeAula {
  musculacao
  spinning
  yoga
  pilates
  jiuJitsu
}

enum TipoContrato {
  Mensal
  Trimestral
  Semestral
  Anual
}

enum NomePlano{
    Bronze
    Prata
    Ouro
}

' ===== STRUCTS  =====

struct Pagamento  {
  valor: Double
  metodo: MetodoPagamento
}

struct PacoteFechado  {
  nome: NomePlano
  complemplaCategorias: List<CategoriaAula>
  valor: Double
}

struct PacoteContratado  {
  pacote: PacoteFechado
  tipoContrato: TipoContrato

}

struct BancoDePacotes <<repository>> {
  catalogo: List<PacoteFechado>
}
' ===== CLASSES =====

class ServicoExtra {
  nome: String
  valor: Double
  tipo: TipoServico
}

class Aula {
  nome: ListNomeAula
  categoria: CategoriaAula
  //horario: Horario
  capacidade: Int
}

class Pessoa {
  nome: String
  idade: Int
  cpf: String
  email: String
  telefone: String
}

class Aluno extends Pessoa {
  matricula: String
  nivelExperiencia: NivelExperiencia
  pacoteContratado: PacoteContratado
}

class Professor extends Pessoa {
  matricula: String
  aulas: List<NomeAula>
}

class GeradorMatriculaAluno {
  contador: Int
}

class GeradorMatriculaProfessor {
  contador: Int
}
'class Contrato {
'  dataInicio: Date
'  ativo: Bool
'}

' ===== RELAÇÕES =====
Pessoa "1" -- "0..1" Aluno
Pessoa "1" -- "0..1" Professor

Aluno "1" --> "1" PacoteFechado 
PacoteFechado "1" --> "1" PacoteContratado
Professor "1" --> "0..*" Aula



@enduml